kubescape-operator:
  alertCRD:
    installDefault: true
  capabilities:
    manageWorkloads: enable
    nodeProfileService: enable
    runtimeDetection: enable
  imagePullSecret:
    server: quay.io
    username: armosec+armosec_ro
  imagePullSecrets: armosec-readonly
  nodeAgent:
    config:
      hostMalwareSensor: disabled
      hostNetworkSensor: disabled
    image:
      repository: quay.io/armosec/node-agent
      tag: image-based-rc5
    resources:
      limits:
        memory: 1000Mi
  operator:
    rulesUpdateConfig:
      enabled: true
      interval: 5m
