kubescape-operator:
  server: api.armosec.io
  nodeAgent:
    config:
      hostMalwareSensor: disabled
      hostNetworkSensor: disabled
    image:
      repository: quay.io/armosec/node-agent
      tag: v0.0.122
    resources:
      limits:
        memory: 1000Mi
