kubescape-operator:
  alertCRD:
    installDefault: false
  capabilities:
    manageWorkloads: enable
    nodeProfileService: enable
    runtimeDetection: enable
  imagePullSecret:
    server: quay.io
    username: armosec+armosec_ro
  imagePullSecrets: armosec-readonly
  nodeAgent:
    config:
      hostMalwareSensor: disabled
      hostNetworkSensor: disabled
    env:
      - name: IGNORERULEBINDINGS
        value: true
    image:
      repository: quay.io/armosec/node-agent
      tag: test-a3db0bf
    resources:
      limits:
        memory: 1000Mi
  operator:
    image:
      tag: v0.2.104
    rulesUpdateConfig:
      enabled: true
      interval: 5m
