kubescape-operator:
  alertCRD:
    installDefault: false
  capabilities:
    backend-storage: enable
    manageWorkloads: enable
    nodeProfileService: enable
    nodeSbomGeneration: disable
    runtimeDetection: enable
  imagePullSecret:
    server: quay.io
    username: armosec+armosec_ro
  imagePullSecrets: armosec-readonly
  nodeAgent:
    config:
      hostMalwareSensor: disable
      hostNetworkSensor: disable
    env:
      - name: IGNORERULEBINDINGS
        value: true
    image:
      repository: quay.io/armosec/node-agent
      tag: backend-storage-rc2
    resources:
      limits:
        memory: 1000Mi
  operator:
    rulesUpdateConfig:
      enabled: true
      interval: 5m
